import type { OpticalOrder } from "./optical-types";

export const LAB_CATALOG = [
	"Essilor",
	"Hoya",
	"Zeiss",
	"Brasor",
	"Wallau",
	"Visionex",
	"Rodenstock",
] as const;

export const FRAME_BRANDS = [
	"Ray-Ban",
	"Oakley",
	"Vogue Eyewear",
	"Armani Exchange",
	"Grazi Massafera",
	"HB - Hot Buttered",
	"Colcci",
	"Prada",
] as const;

export const LENS_OPTIONS = [
	{ name: "Varilux Comfort Max 1.50", lab: "Essilor", defaultPrice: 1890 },
	{ name: "Varilux Physio 3.0 Airwear", lab: "Essilor", defaultPrice: 2450 },
	{ name: "Hoyalux ID Myself 1.60", lab: "Hoya", defaultPrice: 3200 },
	{ name: "Hoyalux Balansis 1.50", lab: "Hoya", defaultPrice: 1650 },
	{
		name: "Zeiss SmartLife Progressive Plus",
		lab: "Zeiss",
		defaultPrice: 2800,
	},
	{
		name: "Zeiss Single Vision ClearView 1.59",
		lab: "Zeiss",
		defaultPrice: 890,
	},
	{ name: "Monofocal Digital Antirreflexo", lab: "Brasor", defaultPrice: 420 },
	{ name: "Multifocal Premium Freeform", lab: "Wallau", defaultPrice: 1190 },
	{ name: "Visão Simples BlueFilter 1.56", lab: "Visionex", defaultPrice: 380 },
];

export const TREATMENT_OPTIONS = [
	{ name: "Crizal Rock", lab: "Essilor", price: 390 },
	{ name: "Crizal Sapphire HR", lab: "Essilor", price: 520 },
	{ name: "Hi-Vision LongLife BlueControl", lab: "Hoya", price: 440 },
	{ name: "DuraVision Platinum", lab: "Zeiss", price: 480 },
	{ name: "Super Antirreflexo Hidrofóbico", lab: "Brasor", price: 180 },
	{ name: "Filtro Luz Azul Premium", lab: "Visionex", price: 150 },
];

export const INITIAL_OPTICAL_ORDERS: OpticalOrder[] = [
	{
		id: "ord_1045",
		orderNumber: "OS-2026-1045A",
		externalLabOrderNumber: "ESS-893021",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_rodrigo", name: "Rodrigo Almeida" },
		doctor: { name: "Dra. Juliana Mendes", crm: "148920/SP" },
		status: "PRONTA_LOJA",
		orderDate: "2026-09-06T14:30:00Z",
		promisedDeliveryDate: "2026-09-12T18:00:00Z", // Vence amanhã
		labSentAt: "2026-09-07T09:00:00Z",
		readyAt: "2026-09-11T11:00:00Z",
		patient: {
			name: "MARIA SOUZA DE OLIVEIRA",
			cpf: "345.892.108-44",
			birthDate: "1978-05-14",
			whatsapp: "(11) 98765-4321",
			secondaryPhone: "(11) 98765-4321",
			email: "maria.souza@gmail.com",
			cep: "01310-100",
			street: "Avenida Paulista",
			number: "1578",
			complement: "Apto 82",
			neighborhood: "Bela Vista",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "RB5228",
			frameBrand: "Ray-Ban",
			frameModel: "RB5228 Acetato Preto",
			framePrice: 650,
			lab: "Essilor",
			lensName: "Varilux Comfort Max 1.50",
			quantity: 1,
			lensPrice: 1890,
			treatment: "Crizal Rock",
			noTreatment: false,
			treatmentPrice: 390,
			diopters: {
				od: {
					esf: "-2.00",
					cil: "-0.75",
					eixo: "180",
					dnp: "31.5",
					alt: "20.0",
				},
				oe: {
					esf: "-1.75",
					cil: "-0.50",
					eixo: "175",
					dnp: "32.0",
					alt: "20.0",
				},
				adicao: "+2.00",
			},
		},
		hasAro2: true,
		isAro2CopyOfAro1: true,
		aro2: {
			frameCode: "VO5322",
			frameBrand: "Vogue Eyewear",
			frameModel: "VO5322 Tartaruga Dourado",
			framePrice: 420,
			lab: "Essilor",
			lensName: "Varilux Comfort Max 1.50 (Solar)",
			quantity: 1,
			lensPrice: 1400,
			treatment: "Crizal Sun UV",
			noTreatment: false,
			treatmentPrice: 280,
			diopters: {
				od: {
					esf: "-2.00",
					cil: "-0.75",
					eixo: "180",
					dnp: "31.5",
					alt: "20.0",
				},
				oe: {
					esf: "-1.75",
					cil: "-0.50",
					eixo: "175",
					dnp: "32.0",
					alt: "20.0",
				},
				adicao: "+2.00",
			},
		},
		financials: {
			subtotalFrames: 1070,
			subtotalLenses: 3290,
			subtotalTreatments: 670,
			discount: 250,
			totalAmount: 4780,
			paymentMode: "SINAL",
			paidAmount: 2000,
			residualAmount: 2780,
			paymentMethod1: "CARTAO_CREDITO",
			paymentAmount1: 2000,
			cardInstallments1: 3,
			cardAuth1: "AUTH-892134",
			notes:
				"Cliente solicitou caprichar na montagem solar. Cobrar residual na entrega.",
		},
		aiAudit: {
			ocrConfidence: 0.98,
			ocrRawText:
				"Varilux Comfort Max - Receita Dra. Juliana Mendes - Transposição validada",
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 1450,
			grossMarginPercent: 69.6,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"OCR identificou prescrição com 98% de precisão sem divergências.",
				"Transposição cilíndrica negativa válida para laboratório Essilor.",
				"Margem comercial de 69.6% acima da meta da loja (60%).",
				"Sinal de 41.8% recebido. Cobrança de residual programada para entrega.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "06/09 14:35",
					title: "Receita Digitalizada via IA OCR",
					detail: "Extração dos graus OD/OE e Adição +2.00 concluída.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "07/09 09:12",
					title: "Pedido EDI Despachado para Lab Essilor",
					detail: "Geração do código de rastreio ESS-893021.",
					status: "ok",
				},
				{
					id: "ev3",
					time: "11/09 10:45",
					title: "Conferência Técnica Final Aprovada",
					detail: "Dioptrias e alturas conferidas no lensômetro digital.",
					status: "ok",
				},
				{
					id: "ev4",
					time: "11/09 11:00",
					title: "Pronto na Loja para Retirada",
					detail: "Disparo de notificação via WhatsApp disponível.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-06T14:30:00Z",
		updatedAt: "2026-09-11T11:00:00Z",
	},
	{
		id: "ord_1046",
		orderNumber: "OS-2026-1046B",
		externalLabOrderNumber: "HOY-441290",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_camila", name: "Camila Santos" },
		doctor: { name: "Dr. Marcelo Carvalho", crm: "88231/RJ" },
		status: "EM_LABORATORIO",
		orderDate: "2026-09-09T16:00:00Z",
		promisedDeliveryDate: "2026-09-15T18:00:00Z", // Vence em 4 dias
		labSentAt: "2026-09-10T08:30:00Z",
		patient: {
			name: "JOÃO RICARDO SANTOS",
			cpf: "219.043.881-09",
			birthDate: "1985-11-23",
			whatsapp: "(11) 97123-8899",
			cep: "04538-133",
			street: "Avenida Brigadeiro Faria Lima",
			number: "3477",
			neighborhood: "Itaim Bibi",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "OX8046",
			frameBrand: "Oakley",
			frameModel: "OX8046 Airdrop Matte Black",
			framePrice: 580,
			lab: "Hoya",
			lensName: "Hoyalux Balansis 1.50",
			quantity: 1,
			lensPrice: 1650,
			treatment: "Hi-Vision LongLife BlueControl",
			noTreatment: false,
			treatmentPrice: 440,
			diopters: {
				od: {
					esf: "+1.25",
					cil: "-1.25",
					eixo: "90",
					dnp: "32.0",
					alt: "21.0",
				},
				oe: {
					esf: "+1.50",
					cil: "-1.00",
					eixo: "85",
					dnp: "32.5",
					alt: "21.0",
				},
				adicao: "+2.25",
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 580,
			subtotalLenses: 1650,
			subtotalTreatments: 440,
			discount: 170,
			totalAmount: 2500,
			paymentMode: "TOTAL",
			paidAmount: 2500,
			residualAmount: 0,
			paymentMethod1: "PIX",
			paymentAmount1: 2500,
			notes: "Quitação total via Pix à vista com desconto especial.",
		},
		aiAudit: {
			ocrConfidence: 0.95,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 780,
			grossMarginPercent: 68.8,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Pagamento 100% quitado no ato da venda.",
				"Custo de laboratório Hoya dentro da tabela contratada.",
				"Tratamento BlueControl verificado para uso intensivo em telas.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "09/09 16:15",
					title: "Venda Registrada e Paga Integralmente",
					detail: "Comprovante Pix validado instantaneamente.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "10/09 08:30",
					title: "Envio ao Lab Hoya",
					detail: "Surfaçagem digital em andamento.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-09T16:00:00Z",
		updatedAt: "2026-09-10T08:30:00Z",
	},
	{
		id: "ord_1047",
		orderNumber: "OS-2026-1047C",
		store: { id: "store_shopping", name: "Óptica Central - Shopping Plaza" },
		seller: { id: "user_rodrigo", name: "Rodrigo Almeida" },
		doctor: { name: "Dr. Roberto Antunes", crm: "74512/MG" },
		status: "CONFERIDA",
		orderDate: "2026-09-07T11:20:00Z",
		promisedDeliveryDate: "2026-09-11T19:00:00Z", // Vence hoje!
		readyAt: "2026-09-11T11:45:00Z",
		patient: {
			name: "ANA CLARA LIMA DE FREITAS",
			cpf: "450.119.782-30",
			birthDate: "1994-08-19",
			whatsapp: "(11) 98111-2233",
			cep: "01415-001",
			street: "Rua Bela Cintra",
			number: "890",
			complement: "Bloco B - 12",
			neighborhood: "Consolação",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "GZ7001",
			frameBrand: "Grazi Massafera",
			frameModel: "GZ7001 Nude Rosé",
			framePrice: 480,
			lab: "Zeiss",
			lensName: "Zeiss Single Vision ClearView 1.59",
			quantity: 1,
			lensPrice: 890,
			treatment: "DuraVision Platinum",
			noTreatment: false,
			treatmentPrice: 480,
			diopters: {
				od: {
					esf: "+0.75",
					cil: "-0.50",
					eixo: "180",
					dnp: "30.0",
					alt: "18.0",
				},
				oe: {
					esf: "+0.50",
					cil: "-0.25",
					eixo: "170",
					dnp: "30.0",
					alt: "18.0",
				},
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 480,
			subtotalLenses: 890,
			subtotalTreatments: 480,
			discount: 100,
			totalAmount: 1750,
			paymentMode: "SINAL",
			paidAmount: 750,
			residualAmount: 1000,
			paymentMethod1: "CARTAO_DEBITO",
			paymentAmount1: 750,
			notes: "Aguardando chegada para conferência e envio à loja física.",
		},
		aiAudit: {
			ocrConfidence: 0.99,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 520,
			grossMarginPercent: 70.2,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Conferência no lensômetro aprovada sem desvio de eixo.",
				"Vencimento de entrega programado para hoje. Contatar cliente se disponível.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "07/09 11:30",
					title: "OS Gerada",
					detail: "Entrada de R$ 750,00 no débito.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "11/09 11:45",
					title: "Conferência Técnica Aprovada",
					detail: "Auditoria de espessura e DNP 30mm/30mm conferida.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-07T11:20:00Z",
		updatedAt: "2026-09-11T11:45:00Z",
	},
	{
		id: "ord_1048",
		orderNumber: "OS-2026-1048D",
		externalLabOrderNumber: "WAL-78190",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_camila", name: "Camila Santos" },
		status: "EM_MONTAGEM",
		orderDate: "2026-09-04T10:00:00Z",
		promisedDeliveryDate: "2026-09-10T18:00:00Z", // Atrasada em 1 dia!
		patient: {
			name: "CARLOS EDUARDO PEREIRA",
			cpf: "189.445.670-88",
			whatsapp: "(11) 99888-7766",
			cep: "03001-000",
			street: "Rua do Gasômetro",
			number: "450",
			neighborhood: "Brás",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "AX1015",
			frameBrand: "Armani Exchange",
			frameModel: "AX1015 Metal Gunmetal",
			framePrice: 620,
			lab: "Wallau",
			lensName: "Multifocal Premium Freeform",
			quantity: 1,
			lensPrice: 1190,
			treatment: "Super Antirreflexo Hidrofóbico",
			noTreatment: false,
			treatmentPrice: 180,
			diopters: {
				od: {
					esf: "-3.50",
					cil: "-1.50",
					eixo: "15",
					dnp: "33.0",
					alt: "22.0",
				},
				oe: {
					esf: "-3.25",
					cil: "-1.75",
					eixo: "165",
					dnp: "33.0",
					alt: "22.0",
				},
				adicao: "+2.50",
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 620,
			subtotalLenses: 1190,
			subtotalTreatments: 180,
			discount: 90,
			totalAmount: 1900,
			paymentMode: "SINAL",
			paidAmount: 900,
			residualAmount: 1000,
			paymentMethod1: "PIX",
			paymentAmount1: 900,
			notes:
				"Atraso no desbaste pelo laboratório. Prioridade de montagem na oficina.",
		},
		aiAudit: {
			ocrConfidence: 0.94,
			prescriptionVerified: true,
			labCostCrosscheck: "WARNING",
			estimatedLabCost: 720,
			grossMarginPercent: 62.1,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "RISK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Alerta de SLA: Promessa de entrega ultrapassada em 1 dia.",
				"Agente IA identificou curvatura de armação grande com miopia moderada (-3.50), exigindo biselamento artesanal.",
				"Notificação de cortesia ao cliente recomendada.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "04/09 10:30",
					title: "Pedido Iniciado",
					detail: "Entrada parcial Pix R$ 900,00.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "10/09 18:00",
					title: "Alerta de Prazo Ultrapassado",
					detail:
						"Montagem na oficina atrasada por ajuste de espessura de borda.",
					status: "warning",
				},
			],
		},
		createdAt: "2026-09-04T10:00:00Z",
		updatedAt: "2026-09-11T09:00:00Z",
	},
	{
		id: "ord_1049",
		orderNumber: "OS-2026-1049E",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_rodrigo", name: "Rodrigo Almeida" },
		status: "DIGITADA",
		orderDate: "2026-09-11T10:15:00Z",
		promisedDeliveryDate: "2026-09-17T18:00:00Z",
		patient: {
			name: "FERNANDA LIMA SILVEIRA",
			cpf: "512.901.344-12",
			whatsapp: "(11) 97654-1122",
			cep: "04038-002",
			street: "Rua Domingos de Morais",
			number: "2187",
			neighborhood: "Vila Mariana",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "HB0921",
			frameBrand: "HB - Hot Buttered",
			frameModel: "HB Shield Acetato Solar",
			framePrice: 490,
			lab: "Visionex",
			lensName: "Visão Simples BlueFilter 1.56",
			quantity: 1,
			lensPrice: 380,
			treatment: "Filtro Luz Azul Premium",
			noTreatment: false,
			treatmentPrice: 150,
			diopters: {
				od: { esf: "-1.00", cil: "0.00", eixo: "", dnp: "29.5", alt: "17.0" },
				oe: { esf: "-1.25", cil: "0.00", eixo: "", dnp: "30.0", alt: "17.0" },
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 490,
			subtotalLenses: 380,
			subtotalTreatments: 150,
			discount: 20,
			totalAmount: 1000,
			paymentMode: "TOTAL",
			paidAmount: 1000,
			residualAmount: 0,
			paymentMethod1: "CARTAO_CREDITO",
			paymentAmount1: 1000,
			cardInstallments1: 4,
			notes: "Venda rápida de balcão concluída.",
		},
		aiAudit: {
			ocrConfidence: 0.99,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 210,
			grossMarginPercent: 79.0,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Venda recém-digitada pronta para agrupamento de corte/envio ao lab.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "11/09 10:15",
					title: "OS Digitada",
					detail: "Aguardando envio no lote diário do laboratório.",
					status: "info",
				},
			],
		},
		createdAt: "2026-09-11T10:15:00Z",
		updatedAt: "2026-09-11T10:15:00Z",
	},
	{
		id: "ord_1050",
		orderNumber: "OS-2026-1050F",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_camila", name: "Camila Santos" },
		status: "ENTREGUE",
		orderDate: "2026-09-01T15:00:00Z",
		promisedDeliveryDate: "2026-09-08T18:00:00Z",
		deliveredAt: "2026-09-08T16:30:00Z",
		patient: {
			name: "ROBERTO MENDES CASTRO",
			cpf: "109.876.543-21",
			whatsapp: "(11) 98456-9900",
			cep: "01311-200",
			street: "Alameda Santos",
			number: "1100",
			neighborhood: "Cerqueira César",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "RB3025",
			frameBrand: "Ray-Ban",
			frameModel: "RB3025 Aviador Clássico Dourado",
			framePrice: 720,
			lab: "Brasor",
			lensName: "Monofocal Digital Antirreflexo",
			quantity: 1,
			lensPrice: 420,
			treatment: "Super Antirreflexo Hidrofóbico",
			noTreatment: false,
			treatmentPrice: 180,
			diopters: {
				od: { esf: "+2.00", cil: "0.00", eixo: "", dnp: "31.0", alt: "19.0" },
				oe: { esf: "+2.00", cil: "0.00", eixo: "", dnp: "31.0", alt: "19.0" },
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 720,
			subtotalLenses: 420,
			subtotalTreatments: 180,
			discount: 70,
			totalAmount: 1250,
			paymentMode: "TOTAL",
			paidAmount: 1250,
			residualAmount: 0,
			paymentMethod1: "CARTAO_DEBITO",
			paymentAmount1: 1250,
			notes: "Cliente provou na loja, ajuste anatômico perfeito nas plaquetas.",
		},
		aiAudit: {
			ocrConfidence: 0.99,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 310,
			grossMarginPercent: 75.2,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: ["Ordem de serviço entregue e concluída com nota máxima."],
			timelineEvents: [
				{
					id: "ev1",
					time: "08/09 16:30",
					title: "Óculos Entregue ao Cliente",
					detail: "Assinatura do termo de retirada coletada.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-01T15:00:00Z",
		updatedAt: "2026-09-08T16:30:00Z",
	},
];

export function generateWhatsAppLink(order: OpticalOrder): string {
	const rawPhone = order.patient.whatsapp.replace(/\D/g, "");
	const cleanPhone = rawPhone.startsWith("55") ? rawPhone : `55${rawPhone}`;

	let msg = `Olá, ${order.patient.name}! Tudo bem?\n\nAqui é da Óptica Central sobre a sua Ordem de Serviço *${order.orderNumber}*.`;

	if (order.status === "PRONTA_LOJA") {
		msg += `\n\n🎉 Seus óculos estão *PRONTOS* para retirada na nossa loja!`;
		if (order.financials.residualAmount > 0) {
			const formattedResidual = new Intl.NumberFormat("pt-BR", {
				style: "currency",
				currency: "BRL",
			}).format(order.financials.residualAmount);
			msg += `\n\nLembramos que há um saldo residual de *${formattedResidual}* para quitação no ato da retirada.`;
		}
		msg += `\n\nTe esperamos para a prova e ajuste de conforto! 😊`;
	} else if (order.status === "EM_LABORATORIO") {
		msg += `\n\nSeus óculos estão em fase de produção especializada no laboratório técnico parceiro. Previsão de chegada: ${new Date(order.promisedDeliveryDate).toLocaleDateString("pt-BR")}.`;
	} else if (order.status === "EM_MONTAGEM") {
		msg += `\n\nAs lentes chegaram do laboratório e já estão na fase final de montagem na armação! Em breve te avisamos assim que estiverem prontos.`;
	} else {
		msg += `\n\nEstamos acompanhando sua confecção de perto! Qualquer dúvida estamos à disposição.`;
	}

	return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(msg)}`;
}
