import type {
	FrameCatalogItem,
	LensCatalogItem,
	MessageTemplateItem,
	OpticalOrder,
	PostSalesRecord,
} from "./optical-types";

export const LAB_CATALOG = [
	"Essilor",
	"Hoya",
	"Zeiss",
	"Brasor",
	"Wallau",
	"Visionex",
	"Rodenstock",
] as const;

export const FRAME_BRANDS = [
	"Ray-Ban",
	"Oakley",
	"Vogue Eyewear",
	"Armani Exchange",
	"Grazi Massafera",
	"HB - Hot Buttered",
	"Colcci",
	"Prada",
] as const;

export const LENS_OPTIONS = [
	{ name: "Varilux Comfort Max 1.50", lab: "Essilor", defaultPrice: 1890 },
	{ name: "Varilux Physio 3.0 Airwear", lab: "Essilor", defaultPrice: 2450 },
	{ name: "Hoyalux ID Myself 1.60", lab: "Hoya", defaultPrice: 3200 },
	{ name: "Hoyalux Balansis 1.50", lab: "Hoya", defaultPrice: 1650 },
	{
		name: "Zeiss SmartLife Progressive Plus",
		lab: "Zeiss",
		defaultPrice: 2800,
	},
	{
		name: "Zeiss Single Vision ClearView 1.59",
		lab: "Zeiss",
		defaultPrice: 890,
	},
	{ name: "Monofocal Digital Antirreflexo", lab: "Brasor", defaultPrice: 420 },
	{ name: "Multifocal Premium Freeform", lab: "Wallau", defaultPrice: 1190 },
	{ name: "Visão Simples BlueFilter 1.56", lab: "Visionex", defaultPrice: 380 },
];

export const TREATMENT_OPTIONS = [
	{ name: "Crizal Rock", lab: "Essilor", price: 390 },
	{ name: "Crizal Sapphire HR", lab: "Essilor", price: 520 },
	{ name: "Hi-Vision LongLife BlueControl", lab: "Hoya", price: 440 },
	{ name: "DuraVision Platinum", lab: "Zeiss", price: 480 },
	{ name: "Super Antirreflexo Hidrofóbico", lab: "Brasor", price: 180 },
	{ name: "Filtro Luz Azul Premium", lab: "Visionex", price: 150 },
];

export const INITIAL_OPTICAL_ORDERS: OpticalOrder[] = [
	{
		id: "ord_1045",
		orderNumber: "OS-2026-1045A",
		externalLabOrderNumber: "ESS-893021",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_rodrigo", name: "Rodrigo Almeida" },
		doctor: { name: "Dra. Juliana Mendes", crm: "148920/SP" },
		status: "PRONTA_LOJA",
		orderDate: "2026-09-06T14:30:00Z",
		promisedDeliveryDate: "2026-09-12T18:00:00Z", // Vence amanhã
		labSentAt: "2026-09-07T09:00:00Z",
		readyAt: "2026-09-11T11:00:00Z",
		patient: {
			name: "MARIA SOUZA DE OLIVEIRA",
			cpf: "345.892.108-44",
			birthDate: "1978-05-14",
			whatsapp: "(11) 98765-4321",
			secondaryPhone: "(11) 98765-4321",
			email: "maria.souza@gmail.com",
			cep: "01310-100",
			street: "Avenida Paulista",
			number: "1578",
			complement: "Apto 82",
			neighborhood: "Bela Vista",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "RB5228",
			frameBrand: "Ray-Ban",
			frameModel: "RB5228 Acetato Preto",
			framePrice: 650,
			lab: "Essilor",
			lensName: "Varilux Comfort Max 1.50",
			quantity: 1,
			lensPrice: 1890,
			treatment: "Crizal Rock",
			noTreatment: false,
			treatmentPrice: 390,
			diopters: {
				od: {
					esf: "-2.00",
					cil: "-0.75",
					eixo: "180",
					dnp: "31.5",
					alt: "20.0",
				},
				oe: {
					esf: "-1.75",
					cil: "-0.50",
					eixo: "175",
					dnp: "32.0",
					alt: "20.0",
				},
				adicao: "+2.00",
			},
		},
		hasAro2: true,
		isAro2CopyOfAro1: true,
		aro2: {
			frameCode: "VO5322",
			frameBrand: "Vogue Eyewear",
			frameModel: "VO5322 Tartaruga Dourado",
			framePrice: 420,
			lab: "Essilor",
			lensName: "Varilux Comfort Max 1.50 (Solar)",
			quantity: 1,
			lensPrice: 1400,
			treatment: "Crizal Sun UV",
			noTreatment: false,
			treatmentPrice: 280,
			diopters: {
				od: {
					esf: "-2.00",
					cil: "-0.75",
					eixo: "180",
					dnp: "31.5",
					alt: "20.0",
				},
				oe: {
					esf: "-1.75",
					cil: "-0.50",
					eixo: "175",
					dnp: "32.0",
					alt: "20.0",
				},
				adicao: "+2.00",
			},
		},
		financials: {
			subtotalFrames: 1070,
			subtotalLenses: 3290,
			subtotalTreatments: 670,
			discount: 250,
			totalAmount: 4780,
			paymentMode: "SINAL",
			paidAmount: 2000,
			residualAmount: 2780,
			paymentMethod1: "CARTAO_CREDITO",
			paymentAmount1: 2000,
			cardInstallments1: 3,
			cardAuth1: "AUTH-892134",
			notes:
				"Cliente solicitou caprichar na montagem solar. Cobrar residual na entrega.",
		},
		aiAudit: {
			ocrConfidence: 0.98,
			ocrRawText:
				"Varilux Comfort Max - Receita Dra. Juliana Mendes - Transposição validada",
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 1450,
			grossMarginPercent: 69.6,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"OCR identificou prescrição com 98% de precisão sem divergências.",
				"Transposição cilíndrica negativa válida para laboratório Essilor.",
				"Margem comercial de 69.6% acima da meta da loja (60%).",
				"Sinal de 41.8% recebido. Cobrança de residual programada para entrega.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "06/09 14:35",
					title: "Receita Digitalizada via IA OCR",
					detail: "Extração dos graus OD/OE e Adição +2.00 concluída.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "07/09 09:12",
					title: "Pedido EDI Despachado para Lab Essilor",
					detail: "Geração do código de rastreio ESS-893021.",
					status: "ok",
				},
				{
					id: "ev3",
					time: "11/09 10:45",
					title: "Conferência Técnica Final Aprovada",
					detail: "Dioptrias e alturas conferidas no lensômetro digital.",
					status: "ok",
				},
				{
					id: "ev4",
					time: "11/09 11:00",
					title: "Pronto na Loja para Retirada",
					detail: "Disparo de notificação via WhatsApp disponível.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-06T14:30:00Z",
		updatedAt: "2026-09-11T11:00:00Z",
	},
	{
		id: "ord_1046",
		orderNumber: "OS-2026-1046B",
		externalLabOrderNumber: "HOY-441290",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_camila", name: "Camila Santos" },
		doctor: { name: "Dr. Marcelo Carvalho", crm: "88231/RJ" },
		status: "EM_LABORATORIO",
		orderDate: "2026-09-09T16:00:00Z",
		promisedDeliveryDate: "2026-09-15T18:00:00Z", // Vence em 4 dias
		labSentAt: "2026-09-10T08:30:00Z",
		patient: {
			name: "JOÃO RICARDO SANTOS",
			cpf: "219.043.881-09",
			birthDate: "1985-11-23",
			whatsapp: "(11) 97123-8899",
			cep: "04538-133",
			street: "Avenida Brigadeiro Faria Lima",
			number: "3477",
			neighborhood: "Itaim Bibi",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "OX8046",
			frameBrand: "Oakley",
			frameModel: "OX8046 Airdrop Matte Black",
			framePrice: 580,
			lab: "Hoya",
			lensName: "Hoyalux Balansis 1.50",
			quantity: 1,
			lensPrice: 1650,
			treatment: "Hi-Vision LongLife BlueControl",
			noTreatment: false,
			treatmentPrice: 440,
			diopters: {
				od: {
					esf: "+1.25",
					cil: "-1.25",
					eixo: "90",
					dnp: "32.0",
					alt: "21.0",
				},
				oe: {
					esf: "+1.50",
					cil: "-1.00",
					eixo: "85",
					dnp: "32.5",
					alt: "21.0",
				},
				adicao: "+2.25",
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 580,
			subtotalLenses: 1650,
			subtotalTreatments: 440,
			discount: 170,
			totalAmount: 2500,
			paymentMode: "TOTAL",
			paidAmount: 2500,
			residualAmount: 0,
			paymentMethod1: "PIX",
			paymentAmount1: 2500,
			notes: "Quitação total via Pix à vista com desconto especial.",
		},
		aiAudit: {
			ocrConfidence: 0.95,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 780,
			grossMarginPercent: 68.8,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Pagamento 100% quitado no ato da venda.",
				"Custo de laboratório Hoya dentro da tabela contratada.",
				"Tratamento BlueControl verificado para uso intensivo em telas.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "09/09 16:15",
					title: "Venda Registrada e Paga Integralmente",
					detail: "Comprovante Pix validado instantaneamente.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "10/09 08:30",
					title: "Envio ao Lab Hoya",
					detail: "Surfaçagem digital em andamento.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-09T16:00:00Z",
		updatedAt: "2026-09-10T08:30:00Z",
	},
	{
		id: "ord_1047",
		orderNumber: "OS-2026-1047C",
		store: { id: "store_shopping", name: "Óptica Central - Shopping Plaza" },
		seller: { id: "user_rodrigo", name: "Rodrigo Almeida" },
		doctor: { name: "Dr. Roberto Antunes", crm: "74512/MG" },
		status: "CONFERIDA",
		orderDate: "2026-09-07T11:20:00Z",
		promisedDeliveryDate: "2026-09-11T19:00:00Z", // Vence hoje!
		readyAt: "2026-09-11T11:45:00Z",
		patient: {
			name: "ANA CLARA LIMA DE FREITAS",
			cpf: "450.119.782-30",
			birthDate: "1994-08-19",
			whatsapp: "(11) 98111-2233",
			cep: "01415-001",
			street: "Rua Bela Cintra",
			number: "890",
			complement: "Bloco B - 12",
			neighborhood: "Consolação",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "GZ7001",
			frameBrand: "Grazi Massafera",
			frameModel: "GZ7001 Nude Rosé",
			framePrice: 480,
			lab: "Zeiss",
			lensName: "Zeiss Single Vision ClearView 1.59",
			quantity: 1,
			lensPrice: 890,
			treatment: "DuraVision Platinum",
			noTreatment: false,
			treatmentPrice: 480,
			diopters: {
				od: {
					esf: "+0.75",
					cil: "-0.50",
					eixo: "180",
					dnp: "30.0",
					alt: "18.0",
				},
				oe: {
					esf: "+0.50",
					cil: "-0.25",
					eixo: "170",
					dnp: "30.0",
					alt: "18.0",
				},
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 480,
			subtotalLenses: 890,
			subtotalTreatments: 480,
			discount: 100,
			totalAmount: 1750,
			paymentMode: "SINAL",
			paidAmount: 750,
			residualAmount: 1000,
			paymentMethod1: "CARTAO_DEBITO",
			paymentAmount1: 750,
			notes: "Aguardando chegada para conferência e envio à loja física.",
		},
		aiAudit: {
			ocrConfidence: 0.99,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 520,
			grossMarginPercent: 70.2,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Conferência no lensômetro aprovada sem desvio de eixo.",
				"Vencimento de entrega programado para hoje. Contatar cliente se disponível.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "07/09 11:30",
					title: "OS Gerada",
					detail: "Entrada de R$ 750,00 no débito.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "11/09 11:45",
					title: "Conferência Técnica Aprovada",
					detail: "Auditoria de espessura e DNP 30mm/30mm conferida.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-07T11:20:00Z",
		updatedAt: "2026-09-11T11:45:00Z",
	},
	{
		id: "ord_1048",
		orderNumber: "OS-2026-1048D",
		externalLabOrderNumber: "WAL-78190",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_camila", name: "Camila Santos" },
		status: "EM_MONTAGEM",
		orderDate: "2026-09-04T10:00:00Z",
		promisedDeliveryDate: "2026-09-10T18:00:00Z", // Atrasada em 1 dia!
		patient: {
			name: "CARLOS EDUARDO PEREIRA",
			cpf: "189.445.670-88",
			whatsapp: "(11) 99888-7766",
			cep: "03001-000",
			street: "Rua do Gasômetro",
			number: "450",
			neighborhood: "Brás",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "AX1015",
			frameBrand: "Armani Exchange",
			frameModel: "AX1015 Metal Gunmetal",
			framePrice: 620,
			lab: "Wallau",
			lensName: "Multifocal Premium Freeform",
			quantity: 1,
			lensPrice: 1190,
			treatment: "Super Antirreflexo Hidrofóbico",
			noTreatment: false,
			treatmentPrice: 180,
			diopters: {
				od: {
					esf: "-3.50",
					cil: "-1.50",
					eixo: "15",
					dnp: "33.0",
					alt: "22.0",
				},
				oe: {
					esf: "-3.25",
					cil: "-1.75",
					eixo: "165",
					dnp: "33.0",
					alt: "22.0",
				},
				adicao: "+2.50",
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 620,
			subtotalLenses: 1190,
			subtotalTreatments: 180,
			discount: 90,
			totalAmount: 1900,
			paymentMode: "SINAL",
			paidAmount: 900,
			residualAmount: 1000,
			paymentMethod1: "PIX",
			paymentAmount1: 900,
			notes:
				"Atraso no desbaste pelo laboratório. Prioridade de montagem na oficina.",
		},
		aiAudit: {
			ocrConfidence: 0.94,
			prescriptionVerified: true,
			labCostCrosscheck: "WARNING",
			estimatedLabCost: 720,
			grossMarginPercent: 62.1,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "RISK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Alerta de SLA: Promessa de entrega ultrapassada em 1 dia.",
				"Agente IA identificou curvatura de armação grande com miopia moderada (-3.50), exigindo biselamento artesanal.",
				"Notificação de cortesia ao cliente recomendada.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "04/09 10:30",
					title: "Pedido Iniciado",
					detail: "Entrada parcial Pix R$ 900,00.",
					status: "ok",
				},
				{
					id: "ev2",
					time: "10/09 18:00",
					title: "Alerta de Prazo Ultrapassado",
					detail:
						"Montagem na oficina atrasada por ajuste de espessura de borda.",
					status: "warning",
				},
			],
		},
		createdAt: "2026-09-04T10:00:00Z",
		updatedAt: "2026-09-11T09:00:00Z",
	},
	{
		id: "ord_1049",
		orderNumber: "OS-2026-1049E",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_rodrigo", name: "Rodrigo Almeida" },
		status: "DIGITADA",
		orderDate: "2026-09-11T10:15:00Z",
		promisedDeliveryDate: "2026-09-17T18:00:00Z",
		patient: {
			name: "FERNANDA LIMA SILVEIRA",
			cpf: "512.901.344-12",
			whatsapp: "(11) 97654-1122",
			cep: "04038-002",
			street: "Rua Domingos de Morais",
			number: "2187",
			neighborhood: "Vila Mariana",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "HB0921",
			frameBrand: "HB - Hot Buttered",
			frameModel: "HB Shield Acetato Solar",
			framePrice: 490,
			lab: "Visionex",
			lensName: "Visão Simples BlueFilter 1.56",
			quantity: 1,
			lensPrice: 380,
			treatment: "Filtro Luz Azul Premium",
			noTreatment: false,
			treatmentPrice: 150,
			diopters: {
				od: { esf: "-1.00", cil: "0.00", eixo: "", dnp: "29.5", alt: "17.0" },
				oe: { esf: "-1.25", cil: "0.00", eixo: "", dnp: "30.0", alt: "17.0" },
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 490,
			subtotalLenses: 380,
			subtotalTreatments: 150,
			discount: 20,
			totalAmount: 1000,
			paymentMode: "TOTAL",
			paidAmount: 1000,
			residualAmount: 0,
			paymentMethod1: "CARTAO_CREDITO",
			paymentAmount1: 1000,
			cardInstallments1: 4,
			notes: "Venda rápida de balcão concluída.",
		},
		aiAudit: {
			ocrConfidence: 0.99,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 210,
			grossMarginPercent: 79.0,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: [
				"Venda recém-digitada pronta para agrupamento de corte/envio ao lab.",
			],
			timelineEvents: [
				{
					id: "ev1",
					time: "11/09 10:15",
					title: "OS Digitada",
					detail: "Aguardando envio no lote diário do laboratório.",
					status: "info",
				},
			],
		},
		createdAt: "2026-09-11T10:15:00Z",
		updatedAt: "2026-09-11T10:15:00Z",
	},
	{
		id: "ord_1050",
		orderNumber: "OS-2026-1050F",
		store: { id: "store_matriz", name: "Óptica Central - Matriz" },
		seller: { id: "user_camila", name: "Camila Santos" },
		status: "ENTREGUE",
		orderDate: "2026-09-01T15:00:00Z",
		promisedDeliveryDate: "2026-09-08T18:00:00Z",
		deliveredAt: "2026-09-08T16:30:00Z",
		patient: {
			name: "ROBERTO MENDES CASTRO",
			cpf: "109.876.543-21",
			whatsapp: "(11) 98456-9900",
			cep: "01311-200",
			street: "Alameda Santos",
			number: "1100",
			neighborhood: "Cerqueira César",
			city: "São Paulo",
			state: "SP",
		},
		aro1: {
			frameCode: "RB3025",
			frameBrand: "Ray-Ban",
			frameModel: "RB3025 Aviador Clássico Dourado",
			framePrice: 720,
			lab: "Brasor",
			lensName: "Monofocal Digital Antirreflexo",
			quantity: 1,
			lensPrice: 420,
			treatment: "Super Antirreflexo Hidrofóbico",
			noTreatment: false,
			treatmentPrice: 180,
			diopters: {
				od: { esf: "+2.00", cil: "0.00", eixo: "", dnp: "31.0", alt: "19.0" },
				oe: { esf: "+2.00", cil: "0.00", eixo: "", dnp: "31.0", alt: "19.0" },
			},
		},
		hasAro2: false,
		isAro2CopyOfAro1: false,
		financials: {
			subtotalFrames: 720,
			subtotalLenses: 420,
			subtotalTreatments: 180,
			discount: 70,
			totalAmount: 1250,
			paymentMode: "TOTAL",
			paidAmount: 1250,
			residualAmount: 0,
			paymentMethod1: "CARTAO_DEBITO",
			paymentAmount1: 1250,
			notes: "Cliente provou na loja, ajuste anatômico perfeito nas plaquetas.",
		},
		aiAudit: {
			ocrConfidence: 0.99,
			prescriptionVerified: true,
			labCostCrosscheck: "APPROVED",
			estimatedLabCost: 310,
			grossMarginPercent: 75.2,
			cylinderTranspositionValid: true,
			diameterThicknessCheck: "OK",
			creditRiskCheck: "LOW",
			agentNotes: ["Ordem de serviço entregue e concluída com nota máxima."],
			timelineEvents: [
				{
					id: "ev1",
					time: "08/09 16:30",
					title: "Óculos Entregue ao Cliente",
					detail: "Assinatura do termo de retirada coletada.",
					status: "ok",
				},
			],
		},
		createdAt: "2026-09-01T15:00:00Z",
		updatedAt: "2026-09-08T16:30:00Z",
	},
];

export function generateWhatsAppLink(order: OpticalOrder): string {
	const rawPhone = order.patient.whatsapp.replace(/\D/g, "");
	const cleanPhone = rawPhone.startsWith("55") ? rawPhone : `55${rawPhone}`;

	let msg = `Olá, ${order.patient.name}! Tudo bem?\n\nAqui é da Óptica Central sobre a sua Ordem de Serviço *${order.orderNumber}*.`;

	if (order.status === "PRONTA_LOJA") {
		msg += `\n\n🎉 Seus óculos estão *PRONTOS* para retirada na nossa loja!`;
		if (order.financials.residualAmount > 0) {
			const formattedResidual = new Intl.NumberFormat("pt-BR", {
				style: "currency",
				currency: "BRL",
			}).format(order.financials.residualAmount);
			msg += `\n\nLembramos que há um saldo residual de *${formattedResidual}* para quitação no ato da retirada.`;
		}
		msg += `\n\nTe esperamos para a prova e ajuste de conforto! 😊`;
	} else if (order.status === "EM_LABORATORIO") {
		msg += `\n\nSeus óculos estão em fase de produção especializada no laboratório técnico parceiro. Previsão de chegada: ${new Date(order.promisedDeliveryDate).toLocaleDateString("pt-BR")}.`;
	} else if (order.status === "EM_MONTAGEM") {
		msg += `\n\nAs lentes chegaram do laboratório e já estão na fase final de montagem na armação! Em breve te avisamos assim que estiverem prontos.`;
	} else {
		msg += `\n\nEstamos acompanhando sua confecção de perto! Qualquer dúvida estamos à disposição.`;
	}

	return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(msg)}`;
}

// -------------------------------------------------------------
// CATÁLOGO INICIAL DE LENTES (ABASTECE A OS COM VARIAÇÃO POR OLHO)
// -------------------------------------------------------------
export const INITIAL_LENS_CATALOG: LensCatalogItem[] = [
	{
		id: "lens_1",
		tipo: "MONOFOCAL",
		familia: "Visão Simples HD",
		produto: "Monofocal Digital HD 1.50 Crizal",
		custo: 85,
		preco: 290,
		indiceRefrativo: "1.50",
		tecnologia: "HD Digital",
		laboratorio: "Sorolab",
		valorPeca: 145,
		tratamentosDisponiveis: ["Antirreflexo Premium", "Filtro Azul", "Clean Coat"],
		ativo: true,
	},
	{
		id: "lens_2",
		tipo: "MONOFOCAL",
		familia: "Single Vision ClearView",
		produto: "Zeiss ClearView Poli 1.59 BlueProtect",
		custo: 130,
		preco: 460,
		indiceRefrativo: "1.59",
		tecnologia: "Freeform Ponto a Ponto",
		laboratorio: "Zeiss",
		valorPeca: 230,
		tratamentosDisponiveis: ["DuraVision Platinum", "BlueProtect", "DriveSafe"],
		ativo: true,
	},
	{
		id: "lens_3",
		tipo: "MONOFOCAL",
		familia: "Nulux High Index",
		produto: "Hoya Nulux 1.67 Asférica Hi-Vision",
		custo: 210,
		preco: 790,
		indiceRefrativo: "1.67",
		tecnologia: "Freeform Asférico",
		laboratorio: "Hoya",
		valorPeca: 395,
		tratamentosDisponiveis: ["Hi-Vision LongLife", "BlueControl"],
		ativo: true,
	},
	{
		id: "lens_4",
		tipo: "MONOFOCAL",
		familia: "Ultra Thin 1.74",
		produto: "Zeiss Single Vision 1.74 DuraVision",
		custo: 380,
		preco: 1450,
		indiceRefrativo: "1.74",
		tecnologia: "Freeform Ultra Delgado",
		laboratorio: "Zeiss",
		valorPeca: 725,
		tratamentosDisponiveis: ["DuraVision Platinum", "LotuTec"],
		ativo: true,
	},
	{
		id: "lens_5",
		tipo: "MULTIFOCAL",
		familia: "Advance Digital",
		produto: "Multifocal Advance Freeform 1.50",
		custo: 260,
		preco: 980,
		indiceRefrativo: "1.50",
		tecnologia: "Freeform",
		laboratorio: "Sorolab",
		valorPeca: 490,
		tratamentosDisponiveis: ["Antirreflexo Premium", "Filtro Luz Azul"],
		ativo: true,
	},
	{
		id: "lens_6",
		tipo: "MULTIFOCAL",
		familia: "Varilux Comfort",
		produto: "Varilux Comfort Max 1.50 Crizal Sapphire",
		custo: 490,
		preco: 1890,
		indiceRefrativo: "1.50",
		tecnologia: "Flex Optim",
		laboratorio: "Essilor",
		valorPeca: 945,
		tratamentosDisponiveis: ["Crizal Sapphire HR", "Crizal Rock", "Optifog"],
		ativo: true,
	},
	{
		id: "lens_7",
		tipo: "MULTIFOCAL",
		familia: "Varilux Physio",
		produto: "Varilux Physio 3.0 Airwear Poli Crizal Rock",
		custo: 620,
		preco: 2450,
		indiceRefrativo: "1.59",
		tecnologia: "W.A.V.E. 2.0 Freeform",
		laboratorio: "Essilor",
		valorPeca: 1225,
		tratamentosDisponiveis: ["Crizal Rock", "Crizal Prevencia"],
		ativo: true,
	},
	{
		id: "lens_8",
		tipo: "MULTIFOCAL",
		familia: "Hoyalux Balansis",
		produto: "Hoyalux Balansis 1.60 LongLife",
		custo: 480,
		preco: 1950,
		indiceRefrativo: "1.60",
		tecnologia: "Dupla Superfície Freeform",
		laboratorio: "Hoya",
		valorPeca: 975,
		tratamentosDisponiveis: ["Hi-Vision LongLife", "BlueControl"],
		ativo: true,
	},
	{
		id: "lens_9",
		tipo: "MULTIFOCAL",
		familia: "Hoyalux Myself",
		produto: "Hoyalux iD Myself 1.67 Personalizada",
		custo: 890,
		preco: 3600,
		indiceRefrativo: "1.67",
		tecnologia: "3D Binocular Eye Model",
		laboratorio: "Hoya",
		valorPeca: 1800,
		tratamentosDisponiveis: ["Hi-Vision LongLife"],
		ativo: true,
	},
	{
		id: "lens_10",
		tipo: "OCUPACIONAL",
		familia: "Desk & Office",
		produto: "Ocupacional Office Pro 1.50",
		custo: 210,
		preco: 780,
		indiceRefrativo: "1.50",
		tecnologia: "Degressiva Digital",
		laboratorio: "Personality",
		valorPeca: 390,
		tratamentosDisponiveis: ["BlueProtect", "Clean Coat"],
		ativo: true,
	},
];

// -------------------------------------------------------------
// CATÁLOGO INICIAL DE PEÇAS (ARMAÇÕES & SOLARES)
// -------------------------------------------------------------
export const INITIAL_FRAME_CATALOG: FrameCatalogItem[] = [
	{
		id: "frame_1",
		tipo: "RECEITUARIO",
		familia: "Acetato Bold",
		produto: "Ray-Ban RX5228 Retangular",
		marca: "Ray-Ban",
		fabricante: "Luxottica",
		tamanhoAro: "53",
		tamanhoPonte: "17",
		fotoUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=300&q=80",
		estoque: 6,
		preco: 690,
		ativo: true,
	},
	{
		id: "frame_2",
		tipo: "RECEITUARIO",
		familia: "Clubmaster Optics",
		produto: "Ray-Ban RX5154 Clubmaster Meio-Aro",
		marca: "Ray-Ban",
		fabricante: "Luxottica",
		tamanhoAro: "51",
		tamanhoPonte: "21",
		fotoUrl: "https://images.unsplash.com/photo-1508296695146-257a814070b4?w=300&q=80",
		estoque: 4,
		preco: 740,
		ativo: true,
	},
	{
		id: "frame_3",
		tipo: "SOLAR",
		familia: "Active Sport",
		produto: "Oakley Holbrook Matte Black OO9102",
		marca: "Oakley",
		fabricante: "Luxottica",
		tamanhoAro: "57",
		tamanhoPonte: "18",
		fotoUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=300&q=80",
		estoque: 12,
		preco: 820,
		ativo: true,
	},
	{
		id: "frame_4",
		tipo: "RECEITUARIO",
		familia: "Elegance Cat-Eye",
		produto: "Vogue VO5352G Tartaruga",
		marca: "Vogue Eyewear",
		fabricante: "Luxottica",
		tamanhoAro: "53",
		tamanhoPonte: "16",
		fotoUrl: "https://images.unsplash.com/photo-1577803645773-f96470509666?w=300&q=80",
		estoque: 9,
		preco: 540,
		ativo: true,
	},
	{
		id: "frame_5",
		tipo: "RECEITUARIO",
		familia: "Titanium Metal",
		produto: "HB Metal Flex 0103 Grafite",
		marca: "HB - Hot Buttered",
		fabricante: "Suntech",
		tamanhoAro: "56",
		tamanhoPonte: "17",
		fotoUrl: "https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=300&q=80",
		estoque: 7,
		preco: 580,
		ativo: true,
	},
	{
		id: "frame_6",
		tipo: "CLIP_ON",
		familia: "Urban Versatile",
		produto: "Colcci Clip-On Magnético C6120",
		marca: "Colcci",
		fabricante: "JR Adamver",
		tamanhoAro: "54",
		tamanhoPonte: "18",
		fotoUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=300&q=80",
		estoque: 11,
		preco: 680,
		ativo: true,
	},
	{
		id: "frame_7",
		tipo: "RECEITUARIO",
		familia: "Delicate Nude",
		produto: "Grazi Massafera GZ3074 Cristal Rose",
		marca: "Grazi Massafera",
		fabricante: "Marchon",
		tamanhoAro: "52",
		tamanhoPonte: "17",
		fotoUrl: "https://images.unsplash.com/photo-1582142407894-ec85a1260a46?w=300&q=80",
		estoque: 8,
		preco: 490,
		ativo: true,
	},
];

// -------------------------------------------------------------
// PÓS-VENDA INICIAL (EXPERIÊNCIA DO CONSUMIDOR)
// -------------------------------------------------------------
export const INITIAL_POST_SALES: PostSalesRecord[] = [
	{
		id: "ps_1",
		orderId: "ord_1045",
		orderNumber: "OS-2026-1045A",
		patientName: "Mariana Silva Costa",
		patientPhone: "11987654321",
		sellerName: "Rodrigo Almeida",
		storeName: "Óptica Central - Matriz",
		deliveredAt: "2026-09-08T16:30:00Z",
		currentStage: "POS_7",
		nextContactDueAt: "2026-09-15T00:00:00Z",
		contactCount: 0,
		notes: "Primeiro multifocal. Checar adaptação na leitura e escadas.",
		createdAt: "2026-09-08T16:30:00Z",
		updatedAt: "2026-09-08T16:30:00Z",
	},
	{
		id: "ps_2",
		orderId: "ord_1042",
		orderNumber: "OS-2026-1042A",
		patientName: "Lucas Fernando Ramos",
		patientPhone: "11998877665",
		sellerName: "Carla Silveira",
		storeName: "Óptica Central - Shopping",
		deliveredAt: "2026-08-16T14:00:00Z",
		currentStage: "POS_30",
		lastContactAt: "2026-08-23T11:00:00Z",
		nextContactDueAt: "2026-09-15T00:00:00Z",
		contactCount: 1,
		feedbackRating: "EXCELLENT",
		notes: "Adaptação perfeita no Pós 7. Checar durabilidade do antirreflexo.",
		createdAt: "2026-08-16T14:00:00Z",
		updatedAt: "2026-08-23T11:00:00Z",
	},
	{
		id: "ps_3",
		orderId: "ord_1038",
		orderNumber: "OS-2026-1038C",
		patientName: "Beatriz Nogueira Lopes",
		patientPhone: "11977665544",
		sellerName: "Rodrigo Almeida",
		storeName: "Óptica Central - Matriz",
		deliveredAt: "2026-06-12T10:00:00Z",
		currentStage: "POS_90",
		lastContactAt: "2026-07-15T15:00:00Z",
		nextContactDueAt: "2026-09-12T00:00:00Z",
		contactCount: 2,
		feedbackRating: "GOOD",
		notes: "Convidar para higienização ultrassônica e revisão de plaquetas cortesia.",
		createdAt: "2026-06-12T10:00:00Z",
		updatedAt: "2026-07-15T15:00:00Z",
	},
	{
		id: "ps_4",
		orderId: "ord_1020",
		orderNumber: "OS-2026-1020B",
		patientName: "Eduardo Camargo Prado",
		patientPhone: "11966554433",
		sellerName: "Carla Silveira",
		storeName: "Óptica Central - Shopping",
		deliveredAt: "2026-04-10T18:00:00Z",
		currentStage: "ATIVO_PROMO",
		lastContactAt: "2026-07-10T12:00:00Z",
		nextContactDueAt: "2026-09-10T00:00:00Z",
		contactCount: 3,
		feedbackRating: "EXCELLENT",
		promoSent: false,
		notes: "Cliente satisfeito. Ofertar promoção especial de 2º par solar graduado.",
		createdAt: "2026-04-10T18:00:00Z",
		updatedAt: "2026-07-10T12:00:00Z",
	},
];

// -------------------------------------------------------------
// TEMPLATES INICIAIS DE MENSAGENS PADRÃO
// -------------------------------------------------------------
export const INITIAL_MESSAGE_TEMPLATES: MessageTemplateItem[] = [
	{
		id: "tmpl_1",
		tipo: "POS_7",
		titulo: "Pós-Venda 7 Dias (Adaptação)",
		texto:
			"Olá, {{cliente}}! Aqui é da {{loja}}. Passando para saber como está sendo sua primeira semana com seus novos óculos (OS: {{os}})? O conforto visual e o ajuste no rosto estão perfeitos?",
		variaveis: ["{{cliente}}", "{{loja}}", "{{os}}"],
		ativo: true,
	},
	{
		id: "tmpl_2",
		tipo: "POS_30",
		titulo: "Pós-Venda 30 Dias (Satisfação)",
		texto:
			"Olá, {{cliente}}! Tudo bem? Daqui a pouco completa 1 mês que você retirou seus óculos na {{loja}}. Como tem sido sua experiência com as lentes {{lente}} no dia a dia?",
		variaveis: ["{{cliente}}", "{{loja}}", "{{lente}}", "{{os}}"],
		ativo: true,
	},
	{
		id: "tmpl_3",
		tipo: "POS_90",
		titulo: "Pós-Venda 90 Dias (Revisão Cortesia)",
		texto:
			"Olá, {{cliente}}! Já se passaram 3 meses da sua compra na {{loja}}. Gostaríamos de convidá-lo para uma revisão preventiva e higienização ultrassônica 100% cortesia dos seus óculos! Quando puder, venha nos visitar.",
		variaveis: ["{{cliente}}", "{{loja}}", "{{os}}"],
		ativo: true,
	},
	{
		id: "tmpl_4",
		tipo: "PRONTA_LOJA",
		titulo: "Aviso de Óculos Pronto para Retirada",
		texto:
			"🎉 Boas notícias, {{cliente}}! Seus óculos da OS {{os}} estão prontos e conferidos na {{loja}} aguardando sua retirada! {{saldo}} Te esperamos para a prova e ajuste.",
		variaveis: ["{{cliente}}", "{{os}}", "{{loja}}", "{{saldo}}"],
		ativo: true,
	},
	{
		id: "tmpl_5",
		tipo: "ATIVO_PROMO",
		titulo: "Ativo Promo - Campanha 2º Par / Renovação",
		texto:
			"Olá, {{cliente}}! Temos uma condição exclusiva para você na {{loja}}: bônus especial de até 50% de desconto na confecção de um 2º par (solar graduado ou óculos de reserva). Essa condição é válida para este mês!",
		variaveis: ["{{cliente}}", "{{loja}}"],
		ativo: true,
	},
	{
		id: "tmpl_6",
		tipo: "COBRANCA_RESIDUAL",
		titulo: "Lembrete Amigável de Saldo Residual",
		texto:
			"Olá, {{cliente}}! Segue o lembrete referente à sua OS {{os}} na {{loja}}. Há um saldo pendente de {{saldo}}. Podemos gerar uma chave Pix para facilitar a quitação?",
		variaveis: ["{{cliente}}", "{{os}}", "{{loja}}", "{{saldo}}"],
		ativo: true,
	},
];

